# Generated by Django 4.2.8 on 2024-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='posts.postattachment'),
        ),
    ]
